### PR TITLE
Added support for RT-Thread RTOS.

### PR DESCRIPTION
**Pull request by balanceTWK**

### CODE REVIEW

**Comment by balanceTWK** [comment]
image

**Review by turon — APPROVED** [review]
LGTM :+1:

We'll have to figure out a way to build the rt-thread target in CI to validate at least at a compilation level.  Perhaps we could add https://github.com/RT-Thread/rt-thread to third_party.  We can discuss future steps.

**Comment by balanceTWK** [comment]
> LGTM 👍
> 
> We'll have to figure out a way to build the rt-thread target in CI to validate at least at a compilation level. Perhaps we could add https://github.com/RT-Thread/rt-thread to third_party. We can discuss future steps.


https://github.com/project-chip/connectedhomeip/tree/master/third_party/freertos
Like FreeRTOS in this link? :-)

Please feel free to contact me.

**Comment by balanceTWK** [comment]
At least I can now make proje-chip/OSAL into a package and let RT-Thread do the CI.

**Pull request merged**
